#!/bin/sh

set -e -x

cd ${GITHUB_WORKSPACE}
export PATH="${PWD}/PLATFORM/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin:${PATH}"
export CROSS_COMPILE=arm-linux-androideabi-
# export CC=arm-linux-androideabi-gcc-
export ARCH=arm
export KCFLAGS=-w
export CONFIG_SECTION_MISMATCH_WARN_ONLY=y
mkdir -p out
make O=out KCFLAGS=-w CONFIG_SECTION_MISMATCH_WARN_ONLY=y ARCH=arm CROSS_COMPILE=arm-linux-androideabi- a02_defconfig
make O=out KCFLAGS=-w CONFIG_SECTION_MISMATCH_WARN_ONLY=y ARCH=arm CROSS_COMPILE=arm-linux-androideabi- -j16

cp out/arch/arm/boot/zImage ${PWD}/zImage
mv zImage boot.img-kernel
rm -rf out
